fixtures:
  repositories:
    archive:   "https://github.com/camptocamp/puppet-archive.git"
    java:   "https://github.com/puppetlabs/puppetlabs-java.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    kafka: "#{source_dir}"